package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.FieldDeclaration_BehaviorDescriptor;

public class AllocateAtributte_BehaviorDescriptor extends FieldDeclaration_BehaviorDescriptor {
  public AllocateAtributte_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.AllocateAtributte";
  }
}
