package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.structure.BehaviorDescriptor;
import jetbrains.mps.smodel.structure.ConceptRegistry;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class AllocateVariableStatement_Behavior {
  private static Class[] PARAMETERS_2025469200171228839 = {SNode.class};

  public static void init(SNode thisNode) {
  }

  public static SNode virtual_getValue_1224857430232(SNode thisNode) {
    return SConceptOperations.createNewNode("jetbrains.mps.baseLanguage.structure.Expression", null);
  }

  public static SNode call_getValue_2025469200171228839(SNode thisNode) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    return (SNode) descriptor.invoke(Object.class, SNodeOperations.cast(thisNode, "rtsj.structure.AllocateVariableStatement"), "virtual_getValue_1224857430232", PARAMETERS_2025469200171228839);
  }

  public static SNode callSuper_getValue_2025469200171228839(SNode thisNode, String callerConceptFqName) {
    return (SNode) BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "rtsj.structure.AllocateVariableStatement"), callerConceptFqName, "virtual_getValue_1224857430232", PARAMETERS_2025469200171228839);
  }
}
