package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class AllocateMemoryStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public AllocateMemoryStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.AllocateMemoryStatement";
  }
}
