package rtsj.behavior;

/*Generated by MPS */


public class AperiodicThread_BehaviorDescriptor extends RealtimeThread_BehaviorDescriptor {
  public AperiodicThread_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.AperiodicThread";
  }
}
