package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class ChangeMode_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public ChangeMode_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.ChangeMode";
  }
}
