package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class EnterMemoryStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public EnterMemoryStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.EnterMemoryStatement";
  }
}
