package rtsj.behavior;

/*Generated by MPS */


public class ImmortalMemory_BehaviorDescriptor extends MemoryArea_BehaviorDescriptor {
  public ImmortalMemory_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.ImmortalMemory";
  }
}
