package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class MainDefinition_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public MainDefinition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.MainDefinition";
  }
}
