package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class MemoryAreaReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public MemoryAreaReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.MemoryAreaReference";
  }
}
