package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ModeChangeRP_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ModeChangeRP_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.ModeChangeRP";
  }
}
