package rtsj.behavior;

/*Generated by MPS */


public class PeriodicThread_BehaviorDescriptor extends RealtimeThread_BehaviorDescriptor {
  public PeriodicThread_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.PeriodicThread";
  }
}
