package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class RawMemoryAccessCreate_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public RawMemoryAccessCreate_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.RawMemoryAccessCreate";
  }
}
