package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class RawMemorySet_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public RawMemorySet_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.RawMemorySet";
  }
}
