package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class RealtimeThreadReference_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public RealtimeThreadReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.RealtimeThreadReference";
  }
}
