package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class ReleaseParametres_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ReleaseParametres_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.ReleaseParametres";
  }
}
