package rtsj.behavior;

/*Generated by MPS */


public class ReleaseParametresSporadic_BehaviorDescriptor extends ReleaseParametres_BehaviorDescriptor {
  public ReleaseParametresSporadic_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.ReleaseParametresSporadic";
  }
}
