package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class RunThreadStatement_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public RunThreadStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.RunThreadStatement";
  }
}
