package rtsj.behavior;

/*Generated by MPS */


public class ScopedMemory_BehaviorDescriptor extends MemoryArea_BehaviorDescriptor {
  public ScopedMemory_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.ScopedMemory";
  }
}
