package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class SizeEstimatorReserve_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public SizeEstimatorReserve_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.SizeEstimatorReserve";
  }
}
