package rtsj.behavior;

/*Generated by MPS */


public class SporadicThread_BehaviorDescriptor extends RealtimeThread_BehaviorDescriptor {
  public SporadicThread_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.SporadicThread";
  }
}
