package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class WedgeThreadStart_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public WedgeThreadStart_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.WedgeThreadStart";
  }
}
