package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class WedgeThreadStop_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public WedgeThreadStop_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.WedgeThreadStop";
  }
}
