package rtsj.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.DropRootRuleContext;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.baseLanguage.behavior.Type_Behavior;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;

public class QueriesGenerated {
  public static boolean dropRootRule_Condition_2740511021581508638(final IOperationContext operationContext, final DropRootRuleContext _context) {
    return true;
  }

  public static boolean dropRootRule_Condition_5373531043073812634(final IOperationContext operationContext, final DropRootRuleContext _context) {
    return true;
  }

  public static boolean dropRootRule_Condition_9175908796922307448(final IOperationContext operationContext, final DropRootRuleContext _context) {
    return true;
  }

  public static boolean dropRootRule_Condition_9175908796922371857(final IOperationContext operationContext, final DropRootRuleContext _context) {
    return true;
  }

  public static boolean dropRootRule_Condition_9175908796922404941(final IOperationContext operationContext, final DropRootRuleContext _context) {
    return true;
  }

  public static boolean dropRootRule_Condition_9175908796922404893(final IOperationContext operationContext, final DropRootRuleContext _context) {
    return true;
  }

  public static boolean dropRootRule_Condition_9175908796922404897(final IOperationContext operationContext, final DropRootRuleContext _context) {
    return true;
  }

  public static boolean dropRootRule_Condition_9175908796922404901(final IOperationContext operationContext, final DropRootRuleContext _context) {
    return true;
  }

  public static boolean dropRootRule_Condition_7960034524145883556(final IOperationContext operationContext, final DropRootRuleContext _context) {
    return true;
  }

  public static boolean baseMappingRule_Condition_6920542396594979954(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "type", "0", "0");
  }

  public static boolean baseMappingRule_Condition_6920542396594979974(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "type", "1", "0");
  }

  public static boolean baseMappingRule_Condition_3711103311464495476(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.getBoolean(_context.getNode(), "generateWaitCycle");
  }

  public static boolean baseMappingRule_Condition_7427614721109169671(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "varType", "0", "0");
  }

  public static boolean baseMappingRule_Condition_7329253685571162763(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "varType", "1", "0");
  }

  public static boolean baseMappingRule_Condition_7329253685571162793(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "varType", "2", "0");
  }

  public static boolean baseMappingRule_Condition_7329253685571162823(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "varType", "3", "0");
  }

  public static boolean baseMappingRule_Condition_7329253685571163054(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "varType", "0", "0");
  }

  public static boolean baseMappingRule_Condition_7329253685571163101(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "varType", "1", "0");
  }

  public static boolean baseMappingRule_Condition_7329253685571163142(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "varType", "2", "0");
  }

  public static boolean baseMappingRule_Condition_7329253685571163183(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.hasValue(_context.getNode(), "varType", "3", "0");
  }

  public static Object propertyMacro_GetPropertyValue_5373531043074065617(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_7960034524145883767(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751630020961(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751630020976(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8019732585718570663(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_8019732585718570631(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751629987056(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "priority", true), "value");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751629988417(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751629988207(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "memory", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751630020557(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751629988279(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "memory", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751630020721(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "thread", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751630020821(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "thread", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751630020889(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "thread", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751630020910(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "thread", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751630020932(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "thread", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_9175908796922316023(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "run" + SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_5373531043074065745(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "memory", true), "memory", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751630021072(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "thread", true), "thread", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751630021082(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "thread", true), "thread", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_63574088154623633(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "startTime", true), "value");
  }

  public static Object propertyMacro_GetPropertyValue_63574088154650440(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "periodTime", true), "value");
  }

  public static Object propertyMacro_GetPropertyValue_63574088154650454(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "cost", true), "value");
  }

  public static Object propertyMacro_GetPropertyValue_63574088154650468(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "deadline", true), "value");
  }

  public static Object propertyMacro_GetPropertyValue_63574088154650572(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "periodTime", true), "value");
  }

  public static Object propertyMacro_GetPropertyValue_63574088154653023(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "cost", true), "value");
  }

  public static Object propertyMacro_GetPropertyValue_63574088154653050(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "deadline", true), "value");
  }

  public static Object propertyMacro_GetPropertyValue_63574088154653170(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "minInterval", true), "value");
  }

  public static Object propertyMacro_GetPropertyValue_63574088154653183(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "cost", true), "value");
  }

  public static Object propertyMacro_GetPropertyValue_63574088154653210(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "deadline", true), "value");
  }

  public static Object propertyMacro_GetPropertyValue_63574088154653233(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(SLinkOperations.getTarget(_context.getNode(), "minInterval", true), "value");
  }

  public static Object propertyMacro_GetPropertyValue_5373531043074065688(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "memory", true), "memory", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_5373531043074059052(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_5373531043073943870(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_5373531043074089605(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "memory", true), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3711103311464471348(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "memory", true), "memory", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3711103311464471329(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_1248562751630021050(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "thread", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_7197056783193750372(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "memory", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_7197056783193750400(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "memory", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_7960034524145883859(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "channel", false), "name");
  }

  public static Object propertyMacro_GetPropertyValue_7960034524145883906(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "channel", false), "name");
  }

  public static Object referenceMacro_GetReferent_1248562751630065245(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "mainPreInit", false), "name");
  }

  public static Object referenceMacro_GetReferent_9175908796922371567(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return "run" + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "startingMode", false), "name");
  }

  public static Object referenceMacro_GetReferent_1248562751630065224(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "mainPostInit", false), "name");
  }

  public static Object referenceMacro_GetReferent_63574088154652937(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "overrunHandler", false), "name");
  }

  public static Object referenceMacro_GetReferent_63574088154652956(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "missHandler", false), "name");
  }

  public static Object referenceMacro_GetReferent_63574088154653087(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "overrunHandler", false), "name");
  }

  public static Object referenceMacro_GetReferent_63574088154653111(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "missHandler", false), "name");
  }

  public static Object referenceMacro_GetReferent_63574088154653247(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "overrunHandler", false), "name");
  }

  public static Object referenceMacro_GetReferent_63574088154653271(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "missHandler", false), "name");
  }

  public static Object referenceMacro_GetReferent_5373531043073949362(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "sizeEstimator", false), "name");
  }

  public static Object referenceMacro_GetReferent_5373531043073949430(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "sizeEstimator", false), "name");
  }

  public static Object referenceMacro_GetReferent_9175908796922349040(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return "run" + SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), "mode", false), "name");
  }

  public static boolean ifMacro_Condition_1248562751630065255(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "mainPreInit", false) != null);
  }

  public static boolean ifMacro_Condition_7197056783193815952(final IOperationContext operationContext, final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(_context.getNode(), "rtsj.structure.ScopedMemory") && SPropertyOperations.getBoolean(SLinkOperations.getTarget(((SNode) _context.getNode()), "wedgeThread", true), "value") == true;
  }

  public static boolean ifMacro_Condition_9175908796922371552(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "startingMode", false) != null);
  }

  public static boolean ifMacro_Condition_1470128220319403239(final IOperationContext operationContext, final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(SLinkOperations.getTarget(_context.getNode(), "startMain", true), "value");
  }

  public static boolean ifMacro_Condition_1248562751630026313(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "mainPostInit", false) != null);
  }

  public static boolean ifMacro_Condition_1470128220319403204(final IOperationContext operationContext, final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(SLinkOperations.getTarget(_context.getNode(), "startMain", true), "value");
  }

  public static boolean ifMacro_Condition_1248562751629988347(final IOperationContext operationContext, final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(SLinkOperations.getTarget(_context.getNode(), "noHeapThread", true), "value") == false;
  }

  public static boolean ifMacro_Condition_1248562751629988384(final IOperationContext operationContext, final IfMacroContext _context) {
    return SPropertyOperations.getBoolean(SLinkOperations.getTarget(_context.getNode(), "noHeapThread", true), "value") == true;
  }

  public static boolean ifMacro_Condition_63574088154650483(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "startTime", true) != null);
  }

  public static boolean ifMacro_Condition_63574088154650522(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "cost", true) != null);
  }

  public static boolean ifMacro_Condition_63574088154650548(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "deadline", true) != null);
  }

  public static boolean ifMacro_Condition_63574088154652914(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "overrunHandler", false) != null);
  }

  public static boolean ifMacro_Condition_63574088154652965(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "missHandler", false) != null);
  }

  public static boolean ifMacro_Condition_63574088154653033(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "cost", true) != null);
  }

  public static boolean ifMacro_Condition_63574088154653060(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "deadline", true) != null);
  }

  public static boolean ifMacro_Condition_63574088154653096(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "overrunHandler", false) != null);
  }

  public static boolean ifMacro_Condition_63574088154653120(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "missHandler", false) != null);
  }

  public static boolean ifMacro_Condition_63574088154653193(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "cost", true) != null);
  }

  public static boolean ifMacro_Condition_63574088154653220(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "deadline", true) != null);
  }

  public static boolean ifMacro_Condition_63574088154653256(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "overrunHandler", false) != null);
  }

  public static boolean ifMacro_Condition_63574088154653280(final IOperationContext operationContext, final IfMacroContext _context) {
    return (SLinkOperations.getTarget(_context.getNode(), "missHandler", false) != null);
  }

  public static boolean ifMacro_Condition_7197056783193816082(final IOperationContext operationContext, final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(_context.getNode(), "memory", true), "rtsj.structure.ScopedMemory") && SPropertyOperations.getBoolean(SLinkOperations.getTarget(((SNode) SLinkOperations.getTarget(_context.getNode(), "memory", true)), "wedgeThread", true), "value") == true;
  }

  public static SNode sourceNodeQuery_5373531043074065602(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_7960034524145883831(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return Type_Behavior.call_getClassExpression_1213877337357(SLinkOperations.getTarget(_context.getNode(), "messageType", true));
  }

  public static SNode sourceNodeQuery_7960034524145883778(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "messageNumber", true);
  }

  public static SNode sourceNodeQuery_1248562751629987077(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "releaseParametres", true);
  }

  public static SNode sourceNodeQuery_1248562751630026247(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_1248562751630026264(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_9175908796922404696(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "priority", true);
  }

  public static SNode sourceNodeQuery_9175908796922405119(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "releaseParametres", true);
  }

  public static SNode sourceNodeQuery_266041992902654102(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return _context.getNode();
  }

  public static SNode sourceNodeQuery_5373531043074059033(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "type", true);
  }

  public static SNode sourceNodeQuery_5373531043074059043(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "type", true);
  }

  public static SNode sourceNodeQuery_5373531043074059062(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return Type_Behavior.call_getClassExpression_1213877337357(SLinkOperations.getTarget(_context.getNode(), "allocater", true));
  }

  public static SNode sourceNodeQuery_6920542396594980053(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "initial", true);
  }

  public static SNode sourceNodeQuery_6920542396594980043(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "maximal", true);
  }

  public static SNode sourceNodeQuery_6920542396594980063(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "initial", true);
  }

  public static SNode sourceNodeQuery_6920542396594980071(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "maximal", true);
  }

  public static SNode sourceNodeQuery_5373531043074052411(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return Type_Behavior.call_getClassExpression_1213877337357(SLinkOperations.getTarget(_context.getNode(), "objectType", true));
  }

  public static SNode sourceNodeQuery_5373531043073949460(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "number", true);
  }

  public static SNode sourceNodeQuery_5373531043074089621(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "memory", true);
  }

  public static SNode sourceNodeQuery_3711103311464471290(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "visibility", true);
  }

  public static SNode sourceNodeQuery_3711103311464471320(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "type", true);
  }

  public static SNode sourceNodeQuery_3711103311464471339(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "type", true);
  }

  public static SNode sourceNodeQuery_3711103311464471369(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return Type_Behavior.call_getClassExpression_1213877337357(SLinkOperations.getTarget(_context.getNode(), "allocater", true));
  }

  public static SNode sourceNodeQuery_3711103311464541525(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "logic", true);
  }

  public static SNode sourceNodeQuery_3711103311464495470(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "logic", true);
  }

  public static SNode sourceNodeQuery_3711103311464557120(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "logic", true);
  }

  public static SNode sourceNodeQuery_3711103311464557130(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "logic", true);
  }

  public static SNode sourceNodeQuery_7329253685571134076(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "memory", true);
  }

  public static SNode sourceNodeQuery_7329253685571046284(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "base", true);
  }

  public static SNode sourceNodeQuery_7329253685571046274(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "size", true);
  }

  public static SNode sourceNodeQuery_7329253685571076423(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "memory", true);
  }

  public static SNode sourceNodeQuery_7329253685571076394(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "offset", true);
  }

  public static SNode sourceNodeQuery_7329253685571162777(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "memory", true);
  }

  public static SNode sourceNodeQuery_7329253685571162786(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "offset", true);
  }

  public static SNode sourceNodeQuery_7329253685571162807(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "memory", true);
  }

  public static SNode sourceNodeQuery_7329253685571162816(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "offset", true);
  }

  public static SNode sourceNodeQuery_7329253685571162837(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "memory", true);
  }

  public static SNode sourceNodeQuery_7329253685571162846(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "offset", true);
  }

  public static SNode sourceNodeQuery_7329253685571162911(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "memory", true);
  }

  public static SNode sourceNodeQuery_7329253685571162886(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "offset", true);
  }

  public static SNode sourceNodeQuery_7329253685571192232(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "value", true);
  }

  public static SNode sourceNodeQuery_7329253685571163076(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "memory", true);
  }

  public static SNode sourceNodeQuery_7329253685571163085(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "offset", true);
  }

  public static SNode sourceNodeQuery_7329253685571192254(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "value", true);
  }

  public static SNode sourceNodeQuery_7329253685571163117(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "memory", true);
  }

  public static SNode sourceNodeQuery_7329253685571163126(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "offset", true);
  }

  public static SNode sourceNodeQuery_7329253685571192264(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "value", true);
  }

  public static SNode sourceNodeQuery_7329253685571163158(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "memory", true);
  }

  public static SNode sourceNodeQuery_7329253685571163167(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "offset", true);
  }

  public static SNode sourceNodeQuery_7329253685571192274(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "value", true);
  }

  public static Iterable sourceNodesQuery_5373531043074065594(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SModelOperations.getNodes(_context.getOriginalInputModel(), "rtsj.structure.MemoryArea");
  }

  public static Iterable sourceNodesQuery_7960034524145883752(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SModelOperations.getNodes(_context.getOriginalInputModel(), "rtsj.structure.InterThreadChannel");
  }

  public static Iterable sourceNodesQuery_1470128220319403113(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SModelOperations.getNodes(_context.getOriginalInputModel(), "rtsj.structure.RealtimeThread");
  }

  public static Iterable sourceNodesQuery_1470128220319403162(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SModelOperations.getNodes(_context.getOriginalInputModel(), "rtsj.structure.RealtimeThread");
  }

  public static Iterable sourceNodesQuery_1248562751629987236(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SModelOperations.getNodes(_context.getOriginalInputModel(), "rtsj.structure.RealtimeThread");
  }

  public static Iterable sourceNodesQuery_9175908796922371686(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "runThreads", true);
  }

  public static Iterable sourceNodesQuery_9175908796922371634(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "runThreads", true);
  }

  public static Iterable sourceNodesQuery_9175908796922371751(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "stopThreads", true);
  }

  public static Iterable sourceNodesQuery_9175908796922404647(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "changePriority", true);
  }

  public static Iterable sourceNodesQuery_9175908796922405089(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "changeRP", true);
  }

  public static Iterable sourceNodesQuery_9175908796922316010(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SModelOperations.getNodes(_context.getOriginalInputModel(), "rtsj.structure.Mode");
  }

  public static Iterable sourceNodesQuery_266041992902654086(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(SLinkOperations.getTarget(_context.getNode(), "body", true), "statement", true);
  }
}
