package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.LocalVariableDeclaration_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public class AllocateVariableStatement_BehaviorDescriptor extends LocalVariableDeclaration_BehaviorDescriptor {
  public AllocateVariableStatement_BehaviorDescriptor() {
  }

  public SNode virtual_getValue_1224857430232(SNode thisNode) {
    return AllocateVariableStatement_Behavior.virtual_getValue_1224857430232(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.AllocateVariableStatement";
  }
}
