package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class InterruptThread_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public InterruptThread_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.InterruptThread";
  }
}
