package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class InterThreadChannelPop_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public InterThreadChannelPop_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.InterThreadChannelPop";
  }
}
