package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class ModeChangePriority_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ModeChangePriority_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.ModeChangePriority";
  }
}
