package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class RawMemoryGet_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public RawMemoryGet_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.RawMemoryGet";
  }
}
