package rtsj.behavior;

/*Generated by MPS */


public class ReleaseParametresAperiodic_BehaviorDescriptor extends ReleaseParametres_BehaviorDescriptor {
  public ReleaseParametresAperiodic_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.ReleaseParametresAperiodic";
  }
}
