package rtsj.behavior;

/*Generated by MPS */


public class ReleaseParametresPeriodic_BehaviorDescriptor extends ReleaseParametres_BehaviorDescriptor {
  public ReleaseParametresPeriodic_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.ReleaseParametresPeriodic";
  }
}
