package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class SizeEstimatorEstimate_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public SizeEstimatorEstimate_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.SizeEstimatorEstimate";
  }
}
