package rtsj.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class WaitForNextPeriod_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public WaitForNextPeriod_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "rtsj.structure.WaitForNextPeriod";
  }
}
