package rtsj.sandbox.sandbox;

/*Generated by MPS */

import javax.realtime.RealtimeThread;

public class CycleWrapperForPerThread implements Runnable {
  private Runnable clazz;

  public CycleWrapperForPerThread(Runnable _clazz) {
    clazz = _clazz;
  }

  public void run() {
    do {
      clazz.run();
    } while (RealtimeThread.waitForNextPeriod());
  }
}
