package rtsj.sandbox.sandbox;

/*Generated by MPS */


public class DummyProductionLine implements ProductionLine {
  public DummyProductionLine(short jarType, short sweetType, long periodMillis) {
  }

  public long getNumberOfJarsMissed() {
    return 0;
  }

  public long getLastJarId() {
    return 0;
  }

  public void getWeighingMachine() {
  }

  public short getSweetType() {
    return ((short) 0);
  }

  public short getJarType() {
    return ((short) 0);
  }
}
