package rtsj.sandbox.sandbox;

/*Generated by MPS */

import rtsj.generator.template.main.InterThreadChannelElement;

public class IntProxy implements InterThreadChannelElement {
  public IntProxy() {
  }

  public void clone(Object target) {
  }
}
