package rtsj.sandbox.sandbox;

/*Generated by MPS */


public class IntProxy implements InterThreadChannelElement<Integer> {
  public IntProxy() {
  }

  public void clone(Integer target) {
  }
}
