package rtsj.sandbox.sandbox;

/*Generated by MPS */


public class ITChanneljava_lang_Integer implements InterThreadChannel {
  private Integer[] objects;
  private int poolSize = 0;
  private int popPointer = 0;
  private int pushPointer = 0;
  private final int EMPTY_POOL = -1;

  public ITChanneljava_lang_Integer(int messageNumber) {
    poolSize = messageNumber;
    popPointer = EMPTY_POOL;
    pushPointer = 0;
    objects = new Integer[messageNumber];
  }

  public Object getEmpty() {
    Integer result = null;

    if (pushPointer == popPointer) {
      throw new ArrayIndexOutOfBoundsException();
    }

    result = objects[pushPointer];

    if (popPointer == EMPTY_POOL) {
      popPointer = pushPointer;
    }

    ++pushPointer;
    if (pushPointer >= poolSize) {
      pushPointer = 0;
    }

    return result;

  }

  public Object getSent() {
    if (popPointer == EMPTY_POOL) {
      return null;
    }
    Object result = objects[popPointer];

    ++popPointer;
    if (popPointer >= poolSize) {
      popPointer = 0;
    }

    if (popPointer == pushPointer) {
      popPointer = EMPTY_POOL;
    }

    return result;
  }
}
