package rtsj.sandbox.sandbox;

/*Generated by MPS */


public class MeasurementManager {
  public MeasurementManager() {
  }

  public Measurement getMeasurement() {
    return new Measurement(0, 0, ((short) 0), ((short) 0), 0);
  }
}
