package rtsj.sandbox.sandbox;

/*Generated by MPS */


public class MonitoringSystemImpl implements MonitoringSystem, Runnable {
  public MonitoringSystemImpl() {
  }

  public void run() {
  }

  public void stopMonitoring() {
  }

  public void startMonitoring(ProductionLine[] productionLines, WorkerConsole console) {
  }
}
