package rtsj.sandbox.sandbox;

/*Generated by MPS */


public class PrimaryWaterLoopImpl implements IWaterLoop {
  private static final double maximalFlow = 120;

  private Double waterFlow = (Double) MainDefinition.allocateVariable("immortalMemory", Double.class);
  private IReactor reactor = null;

  public PrimaryWaterLoopImpl() {
    waterFlow = 10.0;
  }

  public void run() {
    waterFlow = reactor.getTemperature() / 3;
    if (waterFlow > maximalFlow) {
      waterFlow = maximalFlow;
    }
  }

  public void setReactor(IReactor _reactor) {
    reactor = _reactor;
  }

  public Double getFlow() {
    return waterFlow;
  }
}
