package rtsj.sandbox.sandbox;

/*Generated by MPS */

import javax.realtime.LTMemory;
import javax.realtime.RawMemoryAccess;
import javax.realtime.SizeEstimator;

public class Sandbox {
  public Sandbox() {
  }

  public void dummy() {
    MainDefinition.allocateMemory("bla", new LTMemory(2, 8), false);

  }

  public void dummy2() {
    MainDefinition.allocateRawMemoryAccess("rawMemory1", new RawMemoryAccess(null, 0, 10));
    byte b;
    b = MainDefinition.getRawMemoryAccess("rawMemory1").getByte(5);
  }

  public void dummy3() {
    Integer aa = (Integer) MainDefinition.allocateVariable("immortalMemory", Integer.class);
    Integer b = aa;
    System.out.println(b);
  }

  public void dummy4() {
    Thread a = (Thread) MainDefinition.getObjectPool("objectPool1").get();
  }

  public void dumm5() {
    SizeEstimator estimator = new SizeEstimator();
    estimator.reserve(Integer.class, 2);
    System.out.print(estimator.getEstimate());
  }

  public void dummy6() {
    IntProxy message = new IntProxy();
    MainDefinition.getChannel("channel1").push(message);

    IntProxy a = (IntProxy) MainDefinition.getChannel("channel1").pop();
  }
}
