package rtsj.sandbox.sandbox;

/*Generated by MPS */

import javax.realtime.RawMemoryAccess;

public class Sandbox {
  public Sandbox() {
  }

  public void dummy() {
    String a = (String) MainDefinition.getChannel("channel2").getEmpty();
    a = (String) MainDefinition.getChannel("channel2").getEmpty();
  }

  public void dummy2() {
    MainDefinition.allocateRawMemoryAccess("rawMemory1", new RawMemoryAccess(null, 0, 10));
    byte b;
    b = MainDefinition.getRawMemoryAccess("rawMemory1").getByte(5);
  }

  public void dummy3() {
    Integer aa = (Integer) MainDefinition.allocateVariable("immortalMemory", Integer.class);
    Integer b = aa;
    System.out.println(b);
  }
}
