package rtsj.sandbox.sandbox;

/*Generated by MPS */

import javax.realtime.RealtimeThread;
import javax.realtime.ScopedMemory;
import javax.realtime.PriorityParameters;
import javax.realtime.AperiodicParameters;

public class WedgeThread extends RealtimeThread {
  private ScopedMemory memory = null;

  public WedgeThread() {
    super(new PriorityParameters(10), new AperiodicParameters());
  }

  public void setMemory(ScopedMemory _memory) {
    memory = _memory;
  }

  public void run() {
    memory.enter();
    try {
      wait();
    } catch (InterruptedException e) {
      // ignore 
    }
  }
}
