package rtsj.sandbox.sandbox;

/*Generated by MPS */


public interface WorkerConsole {
  public void jarOverfilled(long jarId);
  public void jarUnderfilled(long jarId);
  public void getTotalJarsOverfilled(long jarId);
  public void getTotalJarsUnderfilled(long jarId);
}
