package rtsj.sandbox.sandbox;

/*Generated by MPS */


public interface WorkerConsole {
  public void jarOverfilled(long jarId);
  public void jarUnderfilled(long jarId);
  public long getTotalJarsOverfilled(long jarId);
  public long getTotalJarsUnderfilled(long jarId);
}
