package rtsj.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.style.Style;
import jetbrains.mps.nodeEditor.style.StyleAttributes;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.RefCellCellProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.nodeEditor.EditorManager;
import jetbrains.mps.lang.editor.cellProviders.RefNodeCellProvider;
import jetbrains.mps.nodeEditor.InlineCellProvider;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;

public class ReleaseParametresPeriodic_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_975wbn_a(editorContext, node);
  }

  private EditorCell createCollection_975wbn_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createVertical(editorContext, node);
    editorCell.setCellId("Collection_975wbn_a");
    editorCell.addEditorCell(this.createCollection_975wbn_a0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_975wbn_b0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_975wbn_c0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_975wbn_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_975wbn_e0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_975wbn_f0(editorContext, node));
    editorCell.addEditorCell(this.createCollection_975wbn_g0(editorContext, node));
    return editorCell;
  }

  private EditorCell createCollection_975wbn_a0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_975wbn_a0");
    {
      Style style = editorCell.getStyle();
      style.set(StyleAttributes.SELECTABLE, false);
    }
    editorCell.addEditorCell(this.createConstant_975wbn_a0a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_975wbn_b0a(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_975wbn_c0a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_975wbn_d0a(editorContext, node));
    return editorCell;
  }

  private EditorCell createCollection_975wbn_b0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_975wbn_b0");
    {
      Style style = editorCell.getStyle();
      style.set(StyleAttributes.SELECTABLE, false);
    }
    editorCell.addEditorCell(this.createConstant_975wbn_a1a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_975wbn_b1a(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_975wbn_c1a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_975wbn_d1a(editorContext, node));
    return editorCell;
  }

  private EditorCell createCollection_975wbn_c0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_975wbn_c0");
    {
      Style style = editorCell.getStyle();
      style.set(StyleAttributes.SELECTABLE, false);
    }
    editorCell.addEditorCell(this.createConstant_975wbn_a2a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_975wbn_b2a(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_975wbn_c2a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_975wbn_d2a(editorContext, node));
    return editorCell;
  }

  private EditorCell createCollection_975wbn_d0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_975wbn_d0");
    {
      Style style = editorCell.getStyle();
      style.set(StyleAttributes.SELECTABLE, false);
    }
    editorCell.addEditorCell(this.createConstant_975wbn_a3a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_975wbn_b3a(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_975wbn_c3a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_975wbn_d3a(editorContext, node));
    return editorCell;
  }

  private EditorCell createCollection_975wbn_f0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_975wbn_f0");
    {
      Style style = editorCell.getStyle();
      style.set(StyleAttributes.SELECTABLE, false);
    }
    editorCell.addEditorCell(this.createConstant_975wbn_a5a(editorContext, node));
    editorCell.addEditorCell(this.createConstant_975wbn_b5a(editorContext, node));
    editorCell.addEditorCell(this.createRefCell_975wbn_c5a(editorContext, node));
    return editorCell;
  }

  private EditorCell createCollection_975wbn_g0(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_975wbn_g0");
    {
      Style style = editorCell.getStyle();
      style.set(StyleAttributes.SELECTABLE, false);
    }
    editorCell.addEditorCell(this.createConstant_975wbn_a6a(editorContext, node));
    editorCell.addEditorCell(this.createRefCell_975wbn_b6a(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_975wbn_a0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "cost");
    editorCell.setCellId("Constant_975wbn_a0a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_b0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "=");
    editorCell.setCellId("Constant_975wbn_b0a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_d0a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "ms");
    editorCell.setCellId("Constant_975wbn_d0a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_a1a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "deadline");
    editorCell.setCellId("Constant_975wbn_a1a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_b1a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "=");
    editorCell.setCellId("Constant_975wbn_b1a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_d1a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "ms");
    editorCell.setCellId("Constant_975wbn_d1a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_a2a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "startTime");
    editorCell.setCellId("Constant_975wbn_a2a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_b2a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "=");
    editorCell.setCellId("Constant_975wbn_b2a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_d2a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "ms");
    editorCell.setCellId("Constant_975wbn_d2a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_a3a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "periodTime");
    editorCell.setCellId("Constant_975wbn_a3a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_b3a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "=");
    editorCell.setCellId("Constant_975wbn_b3a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_d3a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "ms");
    editorCell.setCellId("Constant_975wbn_d3a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "");
    editorCell.setCellId("Constant_975wbn_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_a5a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "overrunHandler");
    editorCell.setCellId("Constant_975wbn_a5a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_b5a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "=");
    editorCell.setCellId("Constant_975wbn_b5a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_975wbn_a6a(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "missHandler=");
    editorCell.setCellId("Constant_975wbn_a6a");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createRefCell_975wbn_c5a(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new RefCellCellProvider(node, editorContext);
    provider.setRole("overrunHandler");
    provider.setNoTargetText("<no overrunHandler>");
    EditorCell editorCell;
    provider.setAuxiliaryCellProvider(new ReleaseParametresPeriodic_Editor._Inline_975wbn_a2f0());
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createRefCell_975wbn_b6a(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new RefCellCellProvider(node, editorContext);
    provider.setRole("missHandler");
    provider.setNoTargetText("<no missHandler>");
    EditorCell editorCell;
    provider.setAuxiliaryCellProvider(new ReleaseParametresPeriodic_Editor._Inline_975wbn_a1g0());
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createRefNode_975wbn_c0a(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new RefNodeCellProvider(node, editorContext);
    provider.setRole("cost");
    provider.setNoTargetText("<no cost>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createRefNode_975wbn_c1a(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new RefNodeCellProvider(node, editorContext);
    provider.setRole("deadline");
    provider.setNoTargetText("<no deadline>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createRefNode_975wbn_c2a(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new RefNodeCellProvider(node, editorContext);
    provider.setRole("startTime");
    provider.setNoTargetText("<no startTime>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  private EditorCell createRefNode_975wbn_c3a(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new RefNodeCellProvider(node, editorContext);
    provider.setRole("periodTime");
    provider.setNoTargetText("<no periodTime>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }

  public static class _Inline_975wbn_a2f0 extends InlineCellProvider {
    public _Inline_975wbn_a2f0() {
      super();
    }

    public EditorCell createEditorCell(EditorContext editorContext) {
      return this.createEditorCell(editorContext, this.getSNode());
    }

    public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
      return this.createProperty_975wbn_a0c5a(editorContext, node);
    }

    private EditorCell createProperty_975wbn_a0c5a(EditorContext editorContext, SNode node) {
      CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
      provider.setRole("name");
      provider.setNoTargetText("<no name>");
      provider.setReadOnly(true);
      EditorCell editorCell;
      editorCell = provider.createEditorCell(editorContext);
      editorCell.setCellId("property_name");
      editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
      SNode attributeConcept = provider.getRoleAttribute();
      Class attributeKind = provider.getRoleAttributeClass();
      if (attributeConcept != null) {
        IOperationContext opContext = editorContext.getOperationContext();
        EditorManager manager = EditorManager.getInstanceFromContext(opContext);
        return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
      } else
      return editorCell;
    }
  }

  public static class _Inline_975wbn_a1g0 extends InlineCellProvider {
    public _Inline_975wbn_a1g0() {
      super();
    }

    public EditorCell createEditorCell(EditorContext editorContext) {
      return this.createEditorCell(editorContext, this.getSNode());
    }

    public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
      return this.createProperty_975wbn_a0b6a(editorContext, node);
    }

    private EditorCell createProperty_975wbn_a0b6a(EditorContext editorContext, SNode node) {
      CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
      provider.setRole("name");
      provider.setNoTargetText("<no name>");
      provider.setReadOnly(true);
      EditorCell editorCell;
      editorCell = provider.createEditorCell(editorContext);
      editorCell.setCellId("property_name_1");
      editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
      SNode attributeConcept = provider.getRoleAttribute();
      Class attributeKind = provider.getRoleAttributeClass();
      if (attributeConcept != null) {
        IOperationContext opContext = editorContext.getOperationContext();
        EditorManager manager = EditorManager.getInstanceFromContext(opContext);
        return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
      } else
      return editorCell;
    }
  }
}
