package rtsj.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.nodeEditor.cellProviders.CellProviderWithRole;
import jetbrains.mps.lang.editor.cellProviders.PropertyCellProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.nodeEditor.EditorManager;

public class SizeEstimator_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_bzkbsm_a(editorContext, node);
  }

  private EditorCell createCollection_bzkbsm_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createHorizontal(editorContext, node);
    editorCell.setCellId("Collection_bzkbsm_a");
    editorCell.addEditorCell(this.createConstant_bzkbsm_a0(editorContext, node));
    editorCell.addEditorCell(this.createProperty_bzkbsm_b0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_bzkbsm_c0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_bzkbsm_d0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_bzkbsm_e0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_bzkbsm_f0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_bzkbsm_g0(editorContext, node));
    return editorCell;
  }

  private EditorCell createConstant_bzkbsm_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "SizeEstimator");
    editorCell.setCellId("Constant_bzkbsm_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_bzkbsm_c0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "=");
    editorCell.setCellId("Constant_bzkbsm_c0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_bzkbsm_d0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "new");
    editorCell.setCellId("Constant_bzkbsm_d0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_bzkbsm_e0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "SizeEstimator");
    editorCell.setCellId("Constant_bzkbsm_e0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_bzkbsm_f0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "()");
    editorCell.setCellId("Constant_bzkbsm_f0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createConstant_bzkbsm_g0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, ";");
    editorCell.setCellId("Constant_bzkbsm_g0");
    editorCell.setDefaultText("");
    return editorCell;
  }

  private EditorCell createProperty_bzkbsm_b0(EditorContext editorContext, SNode node) {
    CellProviderWithRole provider = new PropertyCellProvider(node, editorContext);
    provider.setRole("name");
    provider.setNoTargetText("<no name>");
    EditorCell editorCell;
    editorCell = provider.createEditorCell(editorContext);
    editorCell.setCellId("property_name");
    editorCell.setSubstituteInfo(provider.createDefaultSubstituteInfo());
    SNode attributeConcept = provider.getRoleAttribute();
    Class attributeKind = provider.getRoleAttributeClass();
    if (attributeConcept != null) {
      IOperationContext opContext = editorContext.getOperationContext();
      EditorManager manager = EditorManager.getInstanceFromContext(opContext);
      return manager.createRoleAttributeCell(editorContext, attributeConcept, attributeKind, editorCell);
    } else
    return editorCell;
  }
}
