package rtsj.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.FieldDeclaration;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Type;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AllocateAtributte extends FieldDeclaration {
  public static final String concept = "rtsj.structure.AllocateAtributte";
  public static final String MEMORY = "memory";
  public static final String ALLOCATER = "allocater";

  public AllocateAtributte(SNode node) {
    super(node);
  }

  public MemoryAreaReference getMemory() {
    return (MemoryAreaReference) this.getChild(MemoryAreaReference.class, AllocateAtributte.MEMORY);
  }

  public void setMemory(MemoryAreaReference node) {
    super.setChild(AllocateAtributte.MEMORY, node);
  }

  public Type getAllocater() {
    return (Type) this.getChild(Type.class, AllocateAtributte.ALLOCATER);
  }

  public void setAllocater(Type node) {
    super.setChild(AllocateAtributte.ALLOCATER, node);
  }

  public static AllocateAtributte newInstance(SModel sm, boolean init) {
    return (AllocateAtributte) SModelUtil_new.instantiateConceptDeclaration("rtsj.structure.AllocateAtributte", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AllocateAtributte newInstance(SModel sm) {
    return AllocateAtributte.newInstance(sm, false);
  }
}
