package rtsj.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AperiodicThread extends RealtimeThread {
  public static final String concept = "rtsj.structure.AperiodicThread";

  public AperiodicThread(SNode node) {
    super(node);
  }

  public static AperiodicThread newInstance(SModel sm, boolean init) {
    return (AperiodicThread) SModelUtil_new.instantiateConceptDeclaration("rtsj.structure.AperiodicThread", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AperiodicThread newInstance(SModel sm) {
    return AperiodicThread.newInstance(sm, false);
  }
}
