package rtsj.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Statement;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ChangeMode extends Statement {
  public static final String concept = "rtsj.structure.ChangeMode";
  public static final String MODE = "mode";

  public ChangeMode(SNode node) {
    super(node);
  }

  public Mode getMode() {
    return (Mode) this.getReferent(Mode.class, ChangeMode.MODE);
  }

  public void setMode(Mode node) {
    super.setReferent(ChangeMode.MODE, node);
  }

  public static ChangeMode newInstance(SModel sm, boolean init) {
    return (ChangeMode) SModelUtil_new.instantiateConceptDeclaration("rtsj.structure.ChangeMode", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ChangeMode newInstance(SModel sm) {
    return ChangeMode.newInstance(sm, false);
  }
}
