package rtsj.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Statement;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Type;
import jetbrains.mps.baseLanguage.structure.IntegerConstant;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class InterThreadChannel extends Statement implements INamedConcept {
  public static final String concept = "rtsj.structure.InterThreadChannel";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String MESSAGE_TYPE = "messageType";
  public static final String MESSAGE_NUMBER = "messageNumber";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public InterThreadChannel(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(InterThreadChannel.NAME);
  }

  public void setName(String value) {
    this.setProperty(InterThreadChannel.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(InterThreadChannel.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(InterThreadChannel.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(InterThreadChannel.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(InterThreadChannel.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(InterThreadChannel.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(InterThreadChannel.VIRTUAL_PACKAGE, value);
  }

  public Type getMessageType() {
    return (Type) this.getChild(Type.class, InterThreadChannel.MESSAGE_TYPE);
  }

  public void setMessageType(Type node) {
    super.setChild(InterThreadChannel.MESSAGE_TYPE, node);
  }

  public IntegerConstant getMessageNumber() {
    return (IntegerConstant) this.getChild(IntegerConstant.class, InterThreadChannel.MESSAGE_NUMBER);
  }

  public void setMessageNumber(IntegerConstant node) {
    super.setChild(InterThreadChannel.MESSAGE_NUMBER, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(InterThreadChannel.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, InterThreadChannel.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, InterThreadChannel.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(InterThreadChannel.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, InterThreadChannel.SMODEL_ATTRIBUTE, node);
  }

  public static InterThreadChannel newInstance(SModel sm, boolean init) {
    return (InterThreadChannel) SModelUtil_new.instantiateConceptDeclaration("rtsj.structure.InterThreadChannel", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static InterThreadChannel newInstance(SModel sm) {
    return InterThreadChannel.newInstance(sm, false);
  }
}
