package rtsj.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.IntegerConstant;
import jetbrains.mps.baseLanguage.structure.StringLiteral;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class RawMemoryGet extends Expression {
  public static final String concept = "rtsj.structure.RawMemoryGet";
  public static final String VAR_TYPE = "varType";
  public static final String OFFSET = "offset";
  public static final String MEMORY = "memory";

  public RawMemoryGet(SNode node) {
    super(node);
  }

  public RawMemoryType getVarType() {
    String value = super.getProperty(RawMemoryGet.VAR_TYPE);
    return RawMemoryType.parseValue(value);
  }

  public void setVarType(RawMemoryType value) {
    super.setProperty(RawMemoryGet.VAR_TYPE, value.getValueAsString());
  }

  public IntegerConstant getOffset() {
    return (IntegerConstant) this.getChild(IntegerConstant.class, RawMemoryGet.OFFSET);
  }

  public void setOffset(IntegerConstant node) {
    super.setChild(RawMemoryGet.OFFSET, node);
  }

  public StringLiteral getMemory() {
    return (StringLiteral) this.getChild(StringLiteral.class, RawMemoryGet.MEMORY);
  }

  public void setMemory(StringLiteral node) {
    super.setChild(RawMemoryGet.MEMORY, node);
  }

  public static RawMemoryGet newInstance(SModel sm, boolean init) {
    return (RawMemoryGet) SModelUtil_new.instantiateConceptDeclaration("rtsj.structure.RawMemoryGet", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static RawMemoryGet newInstance(SModel sm) {
    return RawMemoryGet.newInstance(sm, false);
  }
}
