package rtsj.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Rtsj_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("95220e4e-a271-48e4-8488-c48145fd3f16(rtsj)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
