package rtsj.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Statement;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class SizeEstimator extends Statement implements INamedConcept {
  public static final String concept = "rtsj.structure.SizeEstimator";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public SizeEstimator(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(SizeEstimator.NAME);
  }

  public void setName(String value) {
    this.setProperty(SizeEstimator.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(SizeEstimator.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(SizeEstimator.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(SizeEstimator.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(SizeEstimator.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(SizeEstimator.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(SizeEstimator.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(SizeEstimator.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, SizeEstimator.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, SizeEstimator.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(SizeEstimator.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, SizeEstimator.SMODEL_ATTRIBUTE, node);
  }

  public static SizeEstimator newInstance(SModel sm, boolean init) {
    return (SizeEstimator) SModelUtil_new.instantiateConceptDeclaration("rtsj.structure.SizeEstimator", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static SizeEstimator newInstance(SModel sm) {
    return SizeEstimator.newInstance(sm, false);
  }
}
