package rtsj.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ImmortalMemory extends MemoryArea {
  public static final String concept = "rtsj.structure.ImmortalMemory";

  public ImmortalMemory(SNode node) {
    super(node);
  }

  public static ImmortalMemory newInstance(SModel sm, boolean init) {
    return (ImmortalMemory) SModelUtil_new.instantiateConceptDeclaration("rtsj.structure.ImmortalMemory", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ImmortalMemory newInstance(SModel sm) {
    return ImmortalMemory.newInstance(sm, false);
  }
}
