package rtsj.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MemoryArea extends BaseConcept implements INamedConcept {
  public static final String concept = "rtsj.structure.MemoryArea";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public MemoryArea(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(MemoryArea.NAME);
  }

  public void setName(String value) {
    this.setProperty(MemoryArea.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(MemoryArea.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(MemoryArea.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(MemoryArea.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(MemoryArea.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(MemoryArea.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(MemoryArea.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(MemoryArea.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, MemoryArea.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, MemoryArea.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(MemoryArea.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, MemoryArea.SMODEL_ATTRIBUTE, node);
  }

  public static MemoryArea newInstance(SModel sm, boolean init) {
    return (MemoryArea) SModelUtil_new.instantiateConceptDeclaration("rtsj.structure.MemoryArea", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MemoryArea newInstance(SModel sm) {
    return MemoryArea.newInstance(sm, false);
  }
}
