package rtsj.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ReleaseParametresAperiodic extends ReleaseParametres {
  public static final String concept = "rtsj.structure.ReleaseParametresAperiodic";

  public ReleaseParametresAperiodic(SNode node) {
    super(node);
  }

  public static ReleaseParametresAperiodic newInstance(SModel sm, boolean init) {
    return (ReleaseParametresAperiodic) SModelUtil_new.instantiateConceptDeclaration("rtsj.structure.ReleaseParametresAperiodic", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ReleaseParametresAperiodic newInstance(SModel sm) {
    return ReleaseParametresAperiodic.newInstance(sm, false);
  }
}
