package rtsj.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Expression;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class WaitForNextPeriod extends Expression {
  public static final String concept = "rtsj.structure.WaitForNextPeriod";

  public WaitForNextPeriod(SNode node) {
    super(node);
  }

  public static WaitForNextPeriod newInstance(SModel sm, boolean init) {
    return (WaitForNextPeriod) SModelUtil_new.instantiateConceptDeclaration("rtsj.structure.WaitForNextPeriod", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static WaitForNextPeriod newInstance(SModel sm) {
    return WaitForNextPeriod.newInstance(sm, false);
  }
}
