package rtsj.sandbox.sandbox;

/*Generated by MPS */


public class DummyWorkerConsole implements WorkerConsole {
  public DummyWorkerConsole() {
  }

  public void getTotalJarsUnderfilled(long jarId) {
  }

  public void getTotalJarsOverfilled(long jarId) {
  }

  public void jarUnderfilled(long jarId) {
  }

  public void jarOverfilled(long jarId) {
  }
}
