package rtsj.sandbox.sandbox;

/*Generated by MPS */


public class InterThreadChannelHolder extends Object {
  private Object[] objects;
  private int poolSize = 0;
  private int popPointer = 0;
  private int pushPointer = 0;
  private final int EMPTY_POOL = -1;

  public InterThreadChannelHolder(Class messageType, int messageNumber) {
    poolSize = messageNumber;
    popPointer = EMPTY_POOL;
    pushPointer = 0;
    objects = new Object[messageNumber];
  }

  public void push(Object object) {
    if (pushPointer == popPointer) {
      throw new ArrayIndexOutOfBoundsException();
    }

    // TODO vyresit problem s clone 
    objects[pushPointer] = object;

    if (popPointer == EMPTY_POOL) {
      popPointer = pushPointer;
    }

    ++pushPointer;
    if (pushPointer >= poolSize) {
      pushPointer = 0;
    }
  }

  public Object pop() {
    if (popPointer == EMPTY_POOL) {
      return null;
    }
    Object result = objects[popPointer];

    ++popPointer;
    if (popPointer >= poolSize) {
      popPointer = 0;
    }

    if (popPointer == pushPointer) {
      popPointer = EMPTY_POOL;
    }

    return result;
  }
}
