package rtsj.sandbox.sandbox;

/*Generated by MPS */


public interface IReactor extends Runnable {
  public Double getTemperature();
  public void setControlRods(IControlRods controlRods);
  public void setWaterLoop(IWaterLoop waterLoop);
}
