package rtsj.sandbox.sandbox;

/*Generated by MPS */


public class Main implements Runnable {
  private static IControlRods controlRods;
  private static IReactor reactor;
  private static IWaterLoop waterLoop;

  public Main() {
  }

  public void run() {
    controlRods = new ControlRodsImpl();
    reactor = new ReactionSimulatorImpl();
    waterLoop = new PrimaryWaterLoopImpl();

    controlRods.setReactor(reactor);
    waterLoop.setReactor(reactor);
    reactor.setControlRods(controlRods);
    reactor.setWaterLoop(waterLoop);
  }

  public static IReactor getReactor() {
    return reactor;
  }

  public static IControlRods getControlRods() {
    return controlRods;
  }

  public static IWaterLoop getWaterLoop() {
    return waterLoop;
  }
}
