package rtsj.sandbox.sandbox;

/*Generated by MPS */


public interface MonitoringSystem {
  public void startMonitoring(ProductionLine[] productionLines, WorkerConsole console);
  public void stopMonitoring();
}
