package rtsj.sandbox.sandbox;

/*Generated by MPS */


public class ObjectPooljava_lang_ThreadElement extends Thread implements ObjectPoolElement {
  private ObjectPoolI objectPool;

  public ObjectPooljava_lang_ThreadElement() {
  }

  public void setObjectPool(ObjectPoolI _objectPool) {
    objectPool = _objectPool;
  }

  public ObjectPoolI getObjectPool() {
    return objectPool;
  }
}
