package rtsj.sandbox.sandbox;

/*Generated by MPS */


public class PrioritySpecifications {
  public static final int POLLING_THREAD_PRIORITY = 38;
  public static final int TRIAGE_THREAD_PRIORITY = 37;

  public PrioritySpecifications() {
  }
}
