package rtsj.sandbox.sandbox;

/*Generated by MPS */


public interface ProductionLine {
  public short getJarType();
  public short getSweetType();
  public WeighingMachine getWeighingMachine();
  public long getLastJarId();
  public long getNumberOfJarsMissed();
}
