package rtsj.sandbox.sandbox;

/*Generated by MPS */


public class Sandbox2 {
  public Sandbox2() {
  }

  public void dummy() {
    int a = (Integer) MainDefinition.allocateVariable("ControlRodsMemory", Integer.class);
    int bb = a;
    System.out.print(bb);
  }
}
