package rtsj.sandbox.sandbox;

/*Generated by MPS */

import javax.realtime.RawMemoryAccess;

public class Sandbox {
  public Sandbox() {
  }

  public void dummy() {
    MainDefinition.getChannel("channel2").push("ss");
    String a = null;
    a = (String) MainDefinition.getChannel("channel2").pop();

    MainDefinition.allocateRawMemoryAccess("bla", new RawMemoryAccess(null, 0, 1000));
    byte b;
    b = MainDefinition.getRawMemoryAccess("bla").getByte(5);
  }
}
