package rtsj.sandbox.sandbox;

/*Generated by MPS */


public class Sandbox {
  public Sandbox() {
  }

  public void dummy() {
    Integer[] a = (Integer[]) MainDefinition.allocaArray("immortalMemory", Integer.class, 5);
    int c = (Integer) MainDefinition.allocateVariable("immortalMemory", Integer.class);
    int d = a[1] + c;
    dummy2(a[1] + c + d);
  }

  public void dummy2(int a) {
  }
}
